name: Run
on:
  push:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the version, default is latest'
        default: "x.x.x"
        type: string
        required: false
        
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
          
      - name: checkout the code
        uses: actions/checkout@v3

      - name: print current MaC
        run: |
              sudo apt install net-tools
              ifconfig
              
      - name: update
        run: |
             sudo apt update && sudo apt upgrade -y 
             
      - name: install network manager
        run: |
             sudo apt install -y macchanger network-manager-gnome
             
      - name: use network manager
        run: |
             sudo systemctl status NetworkManager
             sudo systemctl restart NetworkManager
             
      - name: change mac
        run: |
             sudo systemctl stop NetworkManager
             ip link show
             sudo macchanger --mac=78:2B:CB:47:2F:5A eth0
             sudo systemctl start NetworkManager
             
