name: Run
on:
  push:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the version, default is latest'
        default: "x.x.x"
        type: string
        required: false
        
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
          
      - name: checkout the code
        uses: actions/checkout@v3

      - name: print current MaC
        run: |
              sudo apt install net-tools
              ifconfig
      - name: change mac
        run: |
             sudo apt install macchanger
             sudo apt install network-manager-gnome
             sudo apt upgrade network-manager-gnome
             sudo systemctl restart NetworkManager
             ip link show
             sudo service network-manager status
             sudo service network-manager stop
             sudo macchanger --mac=78:2B:CB:47:2F:5A eth0
             sudo service network-manager start
             
